# terraform/environments/oci-free/main.tf
# Provisions the oci-free environment (ADR 005, ADR 007). State: Terraform
# Cloud (ADR 008) — cloud-agnostic backend, not tied to whichever cloud
# the resources themselves live in.
#
# Prerequisites (manual, cannot be scripted — see docs/how-to/
# provision-oracle-free-tier.md): Oracle Cloud account + API key,
# Terraform Cloud account + `terraform login`.

terraform {
  required_version = ">= 1.6"

  cloud {
    organization = "rastaful" # TODO: confirm exact org name once Terraform Cloud account exists
    workspaces {
      name = "oci-free"
    }
  }

  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 9.0"
    }
  }
}

provider "oci" {
  region = var.region
  # Auth: OCI provider reads ~/.oci/config by default (standard SDK
  # config file, generated by `oci setup config` — see the how-to doc).
  # Never hardcode credentials here or in any .tfvars that gets committed.
}

module "compute" {
  source = "../../modules/oci-compute"

  compartment_id      = var.compartment_id
  availability_domain = var.availability_domain
  ssh_public_key      = var.ssh_public_key
  operator_cidr       = var.operator_cidr
  ocpus               = var.ocpus
  memory_in_gbs       = var.memory_in_gbs
}

variable "compartment_id" {
  type = string
}
variable "region" {
  description = "OCI region — prefer non-US for Always-Free ARM shape availability (Frankfurt/Singapore/Tokyo provision reliably; US regions frequently report 'Out of host capacity'). See ADR 007. (Moved here 2026-09-15 from modules/oci-compute/variables.tf: tflint's terraform_unused_declarations flagged it there for real the first time this session -- the module never referenced var.region, only the provider block here does.)"
  type        = string
}
variable "availability_domain" {
  type = string
}
variable "ssh_public_key" {
  type = string
}
variable "operator_cidr" {
  type = string
}
variable "ocpus" {
  type    = number
  default = 2
}
variable "memory_in_gbs" {
  type    = number
  default = 12
}

output "instance_public_ip" {
  value = module.compute.instance_public_ip
}
